"""
Pydantic models for request/response validation
"""
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime


class ChatRequest(BaseModel):
    """Request model for chat endpoint"""
    message: str = Field(..., description="User's research query")
    thread_id: Optional[str] = Field(None, description="Conversation thread identifier")


class Citation(BaseModel):
    """Source citation model"""
    title: str = Field(..., description="Source title")
    url: str = Field(..., description="Source URL")


class SubQuestion(BaseModel):
    """Research sub-question model"""
    id: str = Field(..., description="Unique identifier for the sub-question")
    question: str = Field(..., description="The sub-question text")
    search_queries: List[str] = Field(..., description="Suggested search queries")
    priority: int = Field(..., description="Priority ranking (1 = highest)")


class ResearchPlan(BaseModel):
    """Research plan generated by Planner Agent"""
    sub_questions: List[SubQuestion] = Field(..., description="List of research sub-questions")
    
    
class ResearchNote(BaseModel):
    """Research findings for a sub-question"""
    sub_question_id: str = Field(..., description="ID of the sub-question")
    evidence_bullets: List[str] = Field(..., description="Evidence points found")
    sources: List[Citation] = Field(..., description="Sources for this sub-question")
    open_questions: List[str] = Field(default_factory=list, description="Identified data gaps")


class ChatMetadata(BaseModel):
    """Metadata about the research process"""
    sub_question_count: int = Field(..., description="Number of sub-questions researched")
    sources_analyzed: int = Field(..., description="Total number of sources")
    completion_timestamp: str = Field(..., description="ISO timestamp of completion")


class ChatResponse(BaseModel):
    """Complete response model"""
    thread_id: str = Field(..., description="Conversation thread identifier")
    query: str = Field(..., description="Original research question")
    executive_summary: str = Field(..., description="5-8 line summary of key findings")
    report: str = Field(..., description="Full research report")
    key_takeaways: List[str] = Field(..., description="Main insights and actionable points")
    limitations: str = Field(..., description="Data gaps, assumptions, and constraints")
    citations: List[Citation] = Field(..., description="Deduplicated list of sources")
    metadata: ChatMetadata = Field(..., description="Research process metadata")


class ErrorResponse(BaseModel):
    """Error response model"""
    error: str = Field(..., description="Error message")
    detail: Optional[str] = Field(None, description="Additional error details")
    thread_id: Optional[str] = Field(None, description="Thread ID if available")
